### ISSUE TITLE
Remove deleted project from the hub

### ISSUE THREAD

**Issue by tboutron** [NFive/hub#11]

**Comment by JoeBiellik** [comment]
This is already [implimented](https://github.com/NFive/hub/blob/master/controllers/github.js#L127), after 5 days a project will be automatically removed from the hub.

**Comment by tboutron** [comment]
Sorry, but i have delete a repository and he is still present (OtherSideRP/plugin-jobmission)

**Comment by nobodyshome** [comment]
Fixed on the current version of the hub.
